"""
Deterministic confidence scoring.

Requirement (user Req 2): the score must come from actual evidence the
pipeline collected, not be generated by the LLM. This module computes it
after LLM extraction, from concrete signals only.

FORMULA (weights sum to 1.0):

  0.20  overview_present      - company_overview is non-empty and >= 20 chars
  0.15  audience_present      - target_audience is non-empty and >= 10 chars
  0.20  has_generic_email     - at least one generic business email found
                                 (contact@/sales@/support@/hello@/info@ etc.)
  0.15  has_leadership        - at least one leadership member extracted
                                 with both name and role
  0.10  has_personal_linkedin - at least one leadership member has a
                                 validated linkedin.com/in/... URL
  0.20  crawl_success_ratio   - (pages successfully fetched) / (pages attempted)
                                 contributes proportionally, not just 0/1

Rationale: this rewards breadth of actually-found evidence rather than any
single field, and crawl_success_ratio ensures a domain that mostly failed to
crawl gets an honestly low score even if the little content it did get
happened to be rich.

Final score is rounded to 2 decimal places and clamped to [0.0, 1.0].
"""

from src.models import CompanyIntelligence, PageFetchStatus

WEIGHTS = {
    "overview_present": 0.20,
    "audience_present": 0.15,
    "has_generic_email": 0.20,
    "has_leadership": 0.15,
    "has_personal_linkedin": 0.10,
    "crawl_success_ratio": 0.20,
}


def compute_confidence(
    intelligence: CompanyIntelligence, pages_crawled: list[PageFetchStatus]
) -> tuple[float, dict]:
    breakdown = {}

    breakdown["overview_present"] = (
        WEIGHTS["overview_present"] if len(intelligence.company_overview.strip()) >= 20 else 0.0
    )
    breakdown["audience_present"] = (
        WEIGHTS["audience_present"] if len(intelligence.target_audience.strip()) >= 10 else 0.0
    )
    breakdown["has_generic_email"] = (
        WEIGHTS["has_generic_email"] if len(intelligence.contact_points.emails) > 0 else 0.0
    )
    leaders_with_name_and_role = [
        m for m in intelligence.leadership if m.name.strip() and m.role.strip()
    ]
    breakdown["has_leadership"] = (
        WEIGHTS["has_leadership"] if len(leaders_with_name_and_role) > 0 else 0.0
    )
    has_linkedin = any(m.linkedin_url for m in intelligence.leadership)
    breakdown["has_personal_linkedin"] = WEIGHTS["has_personal_linkedin"] if has_linkedin else 0.0

    attempted = len(pages_crawled)
    succeeded = len([p for p in pages_crawled if p.status == "ok"])
    ratio = (succeeded / attempted) if attempted > 0 else 0.0
    breakdown["crawl_success_ratio"] = round(WEIGHTS["crawl_success_ratio"] * ratio, 4)

    total = round(sum(breakdown.values()), 2)
    total = max(0.0, min(1.0, total))
    return total, breakdown
